### ISSUE TITLE
[Feature Request] Proxy Support

### ISSUE THREAD

**Issue by mrjester888** [darkalfx/requestrr#30]
I run a bunch of services on a single VM and exposed them on 443 with nginx.  Requestrr fails with this message:

 `warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.`

Google indicates that the app server needs to be coded to support proxied traffic.

**Comment by coder8338** [comment]
Also having an issue with this, using a basic nginx proxy config with:

```
        location /requestrr {
                 proxy_pass http://127.0.0.1:4545;
        }
```

However as there's no option to set the baseurl in requestrr, it's trying to serve all JS on `/`.

I've looked at a few options of setting the baseurl in `system.webServer` but so far nothing has worked.

**Comment by ChaseHall** [comment]
Use sub domains. Proxy's to a "sub folder" cause so many problems, just add a subdomain.

**Comment by coder8338** [comment]
@ChaseHall unfortunately that's not an option with my setup

**Comment by darkalfx** [comment]
This bug has been fixed in v1.0.14, you can now configure a base url with https for Requestrr.
I'm therefore closing this issue!

**Comment by drpoutine** [comment]
> 
> 
> This bug has been fixed in v1.0.14, you can now configure a base url with https for Requestrr.
> I'm therefore closing this issue!

running v1.0.14. its not fixed. 

```Dec 31 21:26:05 server Requestrr.WebApi[2543587]: warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
Dec 31 21:26:05 server Requestrr.WebApi[2543587]:       Failed to determine the https port for redirect.
```


Do you have "Configure for HTTPS" checked in project settings?

**Comment by darkalfx** [comment]
Requestrr itself doesnt support HTTPS, however it now supports being behind an HTTPS reverse proxy.

The proxy would handle the HTTPS, not Requestrr directly.

**Comment by brettpetch** [comment]
Stop the requestrr service. 
In `/opt/requestrr/config`: close to the end of the file, set `"BaseUrl":"/requestrr"`

nginx config:
```nginx
location /requestrr {
  proxy_pass        http://127.0.0.1:4545/requestrr;
  proxy_set_header Host $proxy_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_redirect off;
}
```
