### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8013200A

### ISSUE THREAD

**Issue by mrjester888** [darkalfx/requestrr#75]
OS:  Ubuntu 18.04.5 LTS
Running as a ProxMox container

Downloaded the zip. Unzipped it.  Setup the service file and it fails to start.  

```
Mar 03 00:19:03 media0 systemd[1]: Started Requestrr Daemon.
-- Subject: Unit requestrr.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit requestrr.service has finished starting up.
--
-- The start-up result is RESULT.
Mar 03 00:19:03 media0 Requestrr.WebApi[7779]: Failed to create CoreCLR, HRESULT: 0x8013200A
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Main process exited, code=exited, status=137/n/a
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Failed with result 'exit-code'.
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Service hold-off time over, scheduling restart.
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit requestrr.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mar 03 00:19:03 media0 systemd[1]: Stopped Requestrr Daemon.
-- Subject: Unit requestrr.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit requestrr.service has finished shutting down.
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Start request repeated too quickly.
Mar 03 00:19:03 media0 systemd[1]: requestrr.service: Failed with result 'exit-code'.
Mar 03 00:19:03 media0 systemd[1]: Failed to start Requestrr Daemon.
-- Subject: Unit requestrr.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit requestrr.service has failed.
--
-- The result is RESULT.
```

Trying to run it as root or another user gets the same error.
```
# ./Requestrr.WebApi
Failed to create CoreCLR, HRESULT: 0x8013200A
```
No idea how to troubleshoot this since there are no other logs or events generated that I can find.

**Comment by UnixDaemon12** [comment]
I get the same thing on a proxmox container.  It would connect to discord and crash anytime I ran a command against it from discord.  I restarted the container and now I get the same issue.

**Comment by darkalfx** [comment]
Fixed in latest build

**Comment by mrjester888** [comment]
I am still getting this error.  Moved my old install and extracted to a new folder.  
Tried running as root and as the user that it is configured for.  
```
root@media0:/opt/Requestrr# ./Requestrr.WebApi
Failed to create CoreCLR, HRESULT: 0x8013200A
root@media0:/opt/Requestrr# sudo -u media ./Requestrr.WebApi
Failed to create CoreCLR, HRESULT: 0x8013200A
```

**Comment by darkalfx** [comment]
From what I can tell, the **HRESULT: 0x8013200A** means that something is wrong with the process affinity in your environment.

**Comment by UnixDaemon12** [comment]
The update did fix my issue with Ubuntu 20.04 Proxmox LXC container.  Thank you! 

Mrjester888, have you tried using a 20.04 container instead of 18.04?

**Comment by mrjester888** [comment]
I did not. This is just an additional service on a container running a bunch of others.  I will attempt to do a dist-upgrade and test.
